import {test,expect} from '@playwright/test';
import {mockStation,signIn} from './helpers';
test('staff salaries, partial/full payments, restartable shifts, settings and exports',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));const state=await mockStation(page);await signIn(page);
 await page.getByRole('button',{name:'Staff',exact:true}).click();
 await expect(page.getByText('Ahmad Rahimi',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Edit staff',exact:true}).click();
 await page.getByLabel('Monthly salary (AFN)',{exact:true}).fill('22000');
 await page.getByRole('button',{name:'Save record',exact:true}).click();
 await page.getByRole('button',{name:'Shifts',exact:true}).click();
 await page.getByRole('button',{name:'Start shift',exact:true}).click();
 await page.getByRole('button',{name:'End shift',exact:true}).click();
 await page.getByRole('button',{name:'Start shift',exact:true}).click();
 expect(state().data.shifts.length).toBe(2);
 await page.getByRole('button',{name:'Expenses',exact:true}).click();
 await page.getByRole('button',{name:'Pay salary',exact:true}).click();
 await page.getByLabel('Amount (AFN)',{exact:true}).fill('10000');
 await page.getByRole('button',{name:'Save record',exact:true}).click();
 await page.getByRole('button',{name:'Pay salary',exact:true}).click();
 await expect(page.getByText('Remaining salary: 12,000 ؋',{exact:false})).toBeVisible();
 await page.getByLabel('Amount (AFN)',{exact:true}).fill('12000');
 await page.getByRole('button',{name:'Save record',exact:true}).click();
 await page.getByRole('button',{name:'Record expense',exact:true}).click();
 await page.getByLabel('Expense reason',{exact:true}).fill('Generator maintenance');
 await page.getByLabel('Amount (AFN)',{exact:true}).fill('450');
 await page.getByRole('button',{name:'Save record',exact:true}).click();
 await expect(page.getByText('Generator maintenance')).toBeVisible();
 await page.getByRole('button',{name:'Staff',exact:true}).click();
 await page.getByRole('button',{name:'Staff profile',exact:true}).click();
 await expect(page.getByText('Paid: 22,000 ؋ · Remaining salary: 0 ؋')).toBeVisible();
 await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();
 await page.getByRole('button',{name:'Settings',exact:true}).click();
 await page.getByLabel('Station name',{exact:true}).fill('Kabul Fuel');
 await page.getByLabel('Station address',{exact:true}).fill('Airport Road, Kabul');
 await page.getByRole('combobox',{name:'Theme',exact:true}).selectOption('dark');
 await page.getByRole('button',{name:'Save settings',exact:true}).click();
 await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await expect(page.locator('.sidebar .brand')).toContainText('Kabul Fuel');
 await page.reload();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
 await page.getByRole('button',{name:'Staff',exact:true}).click();
 await page.screenshot({path:'artifacts/staff-dark.png',fullPage:true});
 await page.getByRole('button',{name:'Reports',exact:true}).click();
 await page.getByRole('button',{name:'All time',exact:true}).click();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export complete CSV',exact:true}).click();expect((await download).suggestedFilename()).toContain('allTime');
 expect(state().data.expenses.length).toBe(3);expect(errors).toEqual([]);
});
