import React,{useState,useEffect} from 'react';
import {createRoot} from 'react-dom/client';
import {Fuel,ArrowUpRight,ArrowRight,ShieldCheck,Eye,Globe,LayoutDashboard,Database,Receipt,Wallet,BarChart3,Truck,Clock,Users,Settings,LogOut,Plus,Download,Search,X,ChevronRight,CheckCircle2,AlertTriangle} from 'lucide-react';
import {supabase,initialData,today} from './lib';
import {applyEntry,inPeriod} from './domain';
import {languages,translator} from './i18n';
import './styles.css';
import Management from './Management';
import {OverviewSummary,OverviewDetails} from './OverviewSummary';
import ReportDetails from './ReportDetails';
import {reportCSV,download,payroll} from './management-domain';
const nav=[['overview',LayoutDashboard],['inventory',Database],['pumps',Fuel],['deliveries',Truck],['sales',Receipt],['expenses',Wallet],['reports',BarChart3],['shifts',Clock],['staff',Users],['settings',Settings]];
function readDemo(){try{return JSON.parse(localStorage.getItem('northline-demo'))||initialData();}catch{return initialData();}}
function App(){
 const [lang,setLang]=useState(localStorage.getItem('northline-lang')||'en'),[session,setSession]=useState(null),[demo,setDemo]=useState(false),[authLoading,setAuthLoading]=useState(!!supabase),[data,setData]=useState(initialData),[page,setPage]=useState('overview'),[modal,setModal]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loadError,setLoadError]=useState(false),[notice,setNotice]=useState(''),[period,setPeriod]=useState('daily'),[query,setQuery]=useState(''),[showPassword,setShowPassword]=useState(false);
 const [working,setWorking]=useState(false);
 const t=translator(lang),fmt=n=>new Intl.NumberFormat(lang==='en'?'en-US':lang==='ps'?'ps-AF':'fa-AF',{maximumFractionDigits:2}).format(n),money=n=>`${fmt(n)} ؋`;
 useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='en'?'ltr':'rtl';localStorage.setItem('northline-lang',lang);},[lang]);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data,error})=>{if(error)setError(error.message);setSession(data.session);setAuthLoading(false);}).catch(()=>{setError(t('error'));setAuthLoading(false);});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,s)=>setSession(s));return()=>subscription.unsubscribe();},[]);
 async function load(){setBusy(true);setLoadError(false);try{const {data:row,error}=await supabase.from('station_workspaces').select('data,version').eq('owner_id',session.user.id).maybeSingle();if(error)throw error;if(row){setData({...row.data,_version:row.version});}else{const blank=initialData();blank.sales=[];blank.tanks=blank.tanks.map(x=>({...x,stock:0}));const {error}=await supabase.from('station_workspaces').insert({owner_id:session.user.id,data:blank});if(error)throw error;setData({...blank,_version:0});}}catch(e){setLoadError(true);}finally{setBusy(false);}}
 useEffect(()=>{if(session&&!demo)load();},[session,demo]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),3500);return()=>clearTimeout(timer);},[notice]);
 async function persist(next){if(demo){localStorage.setItem('northline-demo',JSON.stringify(next));setData(next);return;}const version=data._version??0;const payload={...next};delete payload._version;const {data:rows,error}=await supabase.from('station_workspaces').update({data:payload,version:version+1}).eq('owner_id',session.user.id).eq('version',version).select('version');if(error)throw error;if(!rows.length){await load();throw Error('error');}setData({...next,_version:version+1});}
 async function login(e){e.preventDefault();if(!supabase){setError(t('setup'));return;}setBusy(true);setError('');try{const form=new FormData(e.currentTarget);const {error}=await supabase.auth.signInWithPassword({email:form.get('email'),password:form.get('password')});if(error)throw error;}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function logout(){if(!demo){const {error}=await supabase.auth.signOut();if(error){setNotice(t('error'));return;}}setDemo(false);setSession(null);setPage('overview');setError('');}
 async function submit(e){e.preventDefault();setBusy(true);setError('');const f=Object.fromEntries(new FormData(e.currentTarget));const entry={...f,id:crypto.randomUUID(),date:f.date||today()};['liters','price','amount'].forEach(k=>{if(k in entry)entry[k]=Number(entry[k]);});if(modal==='shifts')entry.status='open';try{await persist(applyEntry(data,modal,entry));setModal(null);setNotice(t('saved'));}catch(e){setError(t(e.message in {invalid:1,insufficient:1,capacityError:1}?e.message:'error'));}finally{setBusy(false);}}
 useEffect(()=>{const theme=data.settings?.theme||'light';document.documentElement.dataset.theme=(session||demo)?theme:'light';},[data.settings?.theme,session,demo]);
 const stationName=data.settings?.name||t('brand');
 const stationLabel=data.settings?.name?[data.settings.name,data.settings.address].filter(Boolean).join(' · '):t('station');
 const language=<div className="language"><Globe size={15}/><select aria-label={t('language')} value={lang} onChange={e=>setLang(e.target.value)}>{Object.entries(languages).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>;
 const brand=<div className="brand"><span className="brand-icon"><Fuel size={23}/></span><div>{session||demo?stationName:t('brand')}<small>{t('console')}</small></div></div>;
 const panel=(title,children,action)=> <section className="panel"><div className="panel-head"><h3>{title}</h3>{action}</div>{children}</section>;
 function scene(login=false){return <div className={`scene ${login?'login-scene':''}`} aria-label={t('model')}><div className="scene-grid"/><div className="sun"/><div className="station-model"><div className="roof"><span>NORTHLINE <b> / 24</b></span></div><div className="roof-edge"/><div className="post p1"/><div className="post p2"/><div className="island"/><div className="scene-pumps">{[1,2,3].map((n)=><div className="fuel-pump" key={n}><div className="pump-head"><small>0{n}</small><div className="pump-screen">{n===1?'75.00':n===2?'70.00':'85.00'}<i>AFN / L</i></div></div><div className="pump-base"><Fuel size={21}/></div><div className="hose"/></div>)}</div><div className="road-line"/></div><div className="scene-caption"><span><i className="dot"/>{t(login?'sample':'manual')}</span><span>34.55° N / 69.20° E</span></div></div>;}
 if(authLoading)return <div className="loading">{t('loading')}</div>;
 if(!session&&!demo)return <div className="login-shell"><header>{brand}{language}</header><main className="login-layout"><section className="login-story"><div className="eyebrow"><span className="short-line"/> {session||demo?stationLabel:t('station')}</div><h1>{t('hero')}</h1><p>{t('heroSub')}</p>{scene(true)}<div className="story-bottom"><span>01 / {t('inventory')}</span><span>02 / {t('sales')}</span><span>03 / {t('reports')}</span></div></section><section className="login-card"><div className="access-icon"><ShieldCheck size={25}/></div><div className="eyebrow">{t('secure')}</div><h2>{t('welcome')}</h2><p className="muted">{t('loginSub')}</p><form onSubmit={login} className="login-form"><label>{t('email')}<input name="email" type="email" autoComplete="username" required placeholder="you@station.com" dir="ltr"/></label><label>{t('password')}<div className="password-field"><input name="password" type={showPassword?'text':'password'} autoComplete="current-password" required minLength={6} placeholder="••••••••"/><button type="button" aria-label={t('passwordShow')} onClick={()=>setShowPassword(!showPassword)}><Eye size={18}/></button></div></label>{error&&<div role="alert" className="error">{error}</div>}<button className="primary login-submit" disabled={busy}>{t(busy?'loading':'signIn')}<ArrowRight size={18}/></button></form><div className="divider"><span> {t('console')} </span></div><div className="login-note"><ShieldCheck size={15}/><span>{t('secure')}</span></div></section></main><footer><span>© {new Date().getFullYear()} NORTHLINE</span><span>KABUL, AFGHANISTAN <span className="footer-dot">●</span> {languages[lang]}</span></footer></div>;
 const filteredSales=data.sales.filter(x=>inPeriod(x.date,period,today()));const filteredExpenses=data.expenses.filter(x=>inPeriod(x.date,period,today()));const revenue=filteredSales.reduce((s,x)=>s+x.amount,0),cost=filteredExpenses.reduce((s,x)=>s+x.amount,0),low=data.tanks.filter(x=>x.stock/x.capacity<.25),todaySales=data.sales.filter(x=>x.date===today());
 const metrics=(report=false)=><div className="metrics">{[[report?'revenue':'salesToday',money(report?revenue:todaySales.reduce((s,x)=>s+x.amount,0)),Receipt],[report?'expenses':'dispensed',report?money(cost):fmt(todaySales.reduce((s,x)=>s+x.liters,0))+' L',report?Wallet:Fuel],[report?'net':'available',report?money(revenue-cost):fmt(data.tanks.reduce((s,x)=>s+x.stock,0))+' L',Database],['attention',fmt(low.length+data.pumps.filter(p=>p.status==='service').length),AlertTriangle]].map(([label,value,Icon],i)=><div key={label} className={`metric m${i}`}><div><span>{t(label)}</span><Icon size={17}/></div><strong>{value}</strong><small>{report&&i===2?t('netNote'):t('station')}</small></div>)}</div>;
 const table=(rows,kind)=>{const columns=kind==='staff'?['name','role','phone']:kind==='shifts'?['date','name','status']:['date',...(['sales','deliveries'].includes(kind)?['fuel','liters']:[]),'note','amount'];return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{t(c)}</th>)}{kind==='shifts'&&<th/>}</tr></thead><tbody>{rows.map(row=><tr key={row.id}>{columns.map(c=><td key={c}>{c==='amount'?money(row[c]):['fuel','role','status'].includes(c)?t(row[c]):row[c]??'—'}</td>)}{kind==='shifts'&&<td>{row.status==='open'&&<button disabled={busy} onClick={async()=>{setBusy(true);try{await persist({...data,shifts:data.shifts.map(s=>s.id===row.id?{...s,status:'closed'}:s)});}catch{setNotice(t('error'));}finally{setBusy(false);}}}>{t('closeShift')}</button>}</td>}</tr>)}</tbody></table>{!rows.length&&<div className="empty">{t('empty')}</div>}</div>;};
 function exportCSV(){download(reportCSV(data,period,today()),'northline-'+period+'-'+today()+'.csv','text/csv;charset=utf-8');}
 async function managementPersist(next){setWorking(true);try{await persist(next);}finally{setWorking(false);}}

 return <div className="app"><aside className="sidebar">{brand}<nav>{nav.map(([key,Icon],i)=><React.Fragment key={key}>{[0,4,7].includes(i)&&<div className="nav-label">{t(i===0?'operations':i===4?'finance':'system')}</div>}<button aria-label={t(key)} className={page===key?'active':''} disabled={working} onClick={()=>{setPage(key);setQuery('');}}><Icon size={18}/><span>{t(key)}</span>{page===key&&<ChevronRight size={14}/>}</button></React.Fragment>)}</nav><div className="sidebar-footer"><div className="sidebar-bottom"><div className="station-avatar">N4</div><div><b>{session||demo?stationLabel:t('station')}</b><small>{t(demo?'sample':'connected')}</small></div></div><button className="logout" aria-label={t('logout')} onClick={logout}><LogOut size={17}/>{t('logout')}</button></div></aside><div className="workspace"><div className="topbar"><span><i className="dot"/>{t(demo?'demoMode':'connected')}</span>{language}</div><main className="dashboard"><header className="page-head"><div><div className="eyebrow">{session||demo?stationLabel:t('station')} / {today()}</div><h1>{t(page==='overview'?'stationFloor':page)}</h1><p>{t('overviewSub')}</p></div>{!loadError&&!['staff','shifts','expenses','settings','reports'].includes(page)&&<button className="primary" disabled={busy} onClick={()=>{setError('');setModal(page==='expenses'?'expenses':page==='deliveries'||page==='inventory'?'deliveries':page==='staff'?'staff':page==='shifts'?'shifts':'sales');}}><Plus size={17}/>{t(page==='expenses'?'newExpense':page==='deliveries'||page==='inventory'?'newDelivery':page==='staff'||page==='shifts'?'add':'newSale')}</button>}</header>{loadError?<div className="error">{t('loadError')} <button onClick={load}>{t('retry')}</button></div>:busy&&!modal?<div className="loading">{t('loading')}</div>:<>
 {page==='overview'&&<><OverviewSummary data={data} date={today()} t={t} money={money} fmt={fmt} onNavigate={setPage}/><div className="overview-grid">{panel(t('forecourt'),scene(),<span className="eyebrow">04 / KBL</span>)}{panel(t('tankLevels'),<div className="tanks">{data.tanks.map(tank=><div className="tank" key={tank.id}><div><b>{t(tank.name)}</b><span>{fmt(tank.stock)} <small>L</small></span></div><div className="bar"><i style={{width:Math.min(100,tank.stock/tank.capacity*100)+'%',background:tank.stock/tank.capacity<.25?'var(--red)':''}}/></div><small>{fmt(tank.stock/tank.capacity*100)}% <span>{t(tank.stock/tank.capacity<.25?'low':'healthy')}</span></small></div>)}</div>,<Database size={17}/>)}{panel(t('recent'),table(data.sales.slice(0,5),'sales'),<button className="text-button" onClick={()=>setPage('sales')}>{t('viewAll')} <ArrowUpRight size={14}/></button>)}{panel(t('attention'),<div className="alerts">{low.map(x=><div key={x.id}><AlertTriangle size={17}/><span><b>{t(x.name)}</b><small>{t('low')} · {fmt(x.stock)} L</small></span></div>)}{data.pumps.filter(x=>x.status==='service').map(x=><div key={x.id}><Fuel size={17}/><span><b>{x.id}</b><small>{t('service')}</small></span></div>)}{!low.length&&!data.pumps.some(x=>x.status==='service')&&<p>{t('allClear')}</p>}</div>)}</div><OverviewDetails data={data} date={today()} t={t} money={money} fmt={fmt} onNavigate={setPage}/></>}
 {page==='inventory'&&<div className="inventory-grid">{data.tanks.map(tank=><section className="panel inventory-card" key={tank.id}><div className="flex items-center justify-between"><h3>{t(tank.name)}</h3><Fuel size={20}/></div><div className="tank-vessel"><div style={{height:(tank.stock/tank.capacity*100)+'%'}}/><span>{fmt(tank.stock/tank.capacity*100)}%</span></div><h2>{fmt(tank.stock)} <small>L</small></h2><p>{t('capacity')}: {fmt(tank.capacity)} L</p><div className="inventory-price">{money(tank.price)} / L <span className={tank.stock/tank.capacity<.25?'red':''}>{t(tank.stock/tank.capacity<.25?'low':'healthy')}</span></div></section>)}</div>}
 {page==='pumps'&&<>{scene()}<div className="pump-cards">{data.pumps.map(p=><section className="panel p-5" key={p.id}><Fuel/><h2>{p.id}</h2><p>{t(p.fuel)}</p><label>{t('status')}<select value={p.status} disabled={busy} onChange={async e=>{const status=e.target.value;setBusy(true);try{await persist({...data,pumps:data.pumps.map(x=>x.id===p.id?{...x,status}:x)});}catch{setNotice(t('error'));}finally{setBusy(false);}}}><option value="ready">{t('ready')}</option><option value="service">{t('service')}</option></select></label></section>)}</div><p className="muted">{t('manual')}</p></>}
 {['sales','deliveries'].includes(page)&&panel(t(page),<><div className="table-tools"><Search size={17}/><input aria-label={t('search')} placeholder={t('search')} value={query} onChange={e=>setQuery(e.target.value)}/></div>{table(data[page].filter(x=>Object.values(x).some(v=>String(v).toLowerCase().includes(query.toLowerCase()))),page)}</>)}
 {page==='reports'&&<><div className="report-toolbar"><div className="tabs">{['daily','weekly','monthly','allTime'].map(p=><button className={period===p?'selected':''} key={p} onClick={()=>setPeriod(p)}>{t(p)}</button>)}</div><button onClick={exportCSV}><Download size={16}/>{t('exportAll')}</button><button onClick={()=>{const payload={...data};delete payload._version;download(JSON.stringify({exportedAt:new Date().toISOString(),...payload},null,2),'northline-all-data-'+today()+'.json','application/json');}}>{t('backup')}</button></div><p className="muted">{t('reportScope')}</p>{metrics(true)}{panel(t('fuelMix'),<div className="report-bars">{data.tanks.map(tank=>{const amount=filteredSales.filter(x=>x.fuel===tank.id).reduce((s,x)=>s+x.amount,0);return <div key={tank.id}><span>{t(tank.name)}</span><div className="bar"><i style={{width:(revenue?amount/revenue*100:0)+'%'}}/></div><b>{money(amount)}</b></div>;})}</div>)}<div className="mt-5">{panel(t('sales'),table(filteredSales,'sales'))}</div><div className="mt-5">{panel(t('expenses'),table(filteredExpenses,'expenses'))}</div></>}
 {['staff','shifts','expenses','settings'].includes(page)&&<Management key={page} page={page} data={data} persist={managementPersist} t={t} money={money} language={language} onNotice={setNotice}/>}

 </>}<div className="dashboard-footer"><span>{stationName} / {t('console')}</span><span>AFN · ASIA/KABUL</span></div></main></div>
 {modal&&<div className="modal-overlay" onClick={e=>{if(e.target===e.currentTarget&&!busy)setModal(null);}}><section className="modal panel" role="dialog" aria-modal="true" aria-label={t(modal)} onKeyDown={e=>{if(e.key==='Escape'&&!busy)setModal(null);if(e.key==='Tab'){const els=[...e.currentTarget.querySelectorAll('button:not(:disabled),input,select')];const first=els[0],last=els.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><div className="panel-head"><h3>{t(modal)} · {t('add')}</h3><button aria-label={t('cancel')} disabled={busy} onClick={()=>setModal(null)}><X size={18}/></button></div><form onSubmit={submit} className="entry-form"><label>{t('date')}<input autoFocus type="date" name="date" defaultValue={today()} max={today()} required/></label>{['sales','deliveries'].includes(modal)&&<><label>{t('fuel')}<select name="fuel">{data.tanks.map(x=><option key={x.id} value={x.id}>{t(x.name)}</option>)}</select></label><div className="form-row"><label>{t('liters')}<input name="liters" type="number" min="0.01" step="0.01" required/></label><label>{t('price')}<input name="price" type="number" min="0.01" step="0.01" required/></label></div></>}{modal==='expenses'&&<label>{t('amount')}<input name="amount" type="number" min="0.01" step="0.01" required/></label>}{['staff','shifts'].includes(modal)&&<label>{t('name')}<input name="name" required maxLength={100}/></label>}{modal==='staff'&&<><label>{t('role')}<select name="role"><option value="operator">{t('operator')}</option><option value="manager">{t('manager')}</option></select></label><label>{t('phone')}<input name="phone" type="tel" maxLength={30}/></label></>}<label>{t('note')}<input name="note" required={modal==='expenses'} maxLength={250}/></label>{error&&<div className="error" role="alert">{error}</div>}<div className="modal-actions"><button type="button" disabled={busy} onClick={()=>setModal(null)}>{t('cancel')}</button><button className="primary" disabled={busy}>{t(busy?'loading':'save')}</button></div></form></section></div>}{notice&&<div className="toast" role="status"><CheckCircle2 size={18}/>{notice}</div>}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
