import React,{useState} from 'react';
import {Plus,Wallet,Clock,Users,X} from 'lucide-react';
import {payroll,paySalary,saveStaff,toggleShift} from './management-domain';
import {today} from './lib';

export default function Management({page,data,persist,t,money,language,onNotice}){
 const [dialog,setDialog]=useState(null),[error,setError]=useState(''),[saving,setSaving]=useState(false),[month,setMonth]=useState(today().slice(0,7)),[selected,setSelected]=useState(''),[profile,setProfile]=useState(null);
 const open=(type,id='')=>{setError('');setSelected(id||data.staff[0]?.id||'');setDialog(type);};
 async function commit(next){setSaving(true);setError('');try{await persist(next);setDialog(null);onNotice(t('saved'));return true;}catch{setError(t('error'));return false;}finally{setSaving(false);}}
 async function submit(event){event.preventDefault();setError('');const values=Object.fromEntries(new FormData(event.currentTarget));try{
  if(dialog==='staff'){await commit(saveStaff(data,{...values,name:values.name.trim(),salary:Number(values.salary),date:values.date||today()},selected));}
  if(dialog==='salary'){await commit(paySalary(data,{...values,amount:Number(values.amount),salaryMonth:month,staffId:selected}));}
  if(dialog==='expense'){if(!values.reason.trim()||Number(values.amount)<=0)throw Error('invalid');await commit({...data,expenses:[{...values,amount:Number(values.amount),note:values.reason.trim(),reason:values.reason.trim(),category:'general',id:crypto.randomUUID()},...data.expenses]});}
 }catch(e){setError(t(e.message==='overpayment'?'overpayment':'invalid'));}}
 const staff=data.staff.find(s=>s.id===selected),balance=payroll(data,selected,month);
 const time=value=>value?new Intl.DateTimeFormat(document.documentElement.lang==='en'?'en-GB':document.documentElement.lang==='ps'?'ps-AF':'fa-AF',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Kabul'}).format(new Date(value)):'—';
 const history=rows=><div className="table-wrap"><table><thead><tr>{['date','reason','salaryMonth','amount'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{rows.map(e=><tr key={e.id}><td>{e.date}</td><td>{e.category==='salary'?`${t('salaryPayment')} · ${e.staffName||data.staff.find(s=>s.id===e.staffId)?.name||''}`:e.reason||e.note}</td><td>{e.salaryMonth||'—'}</td><td>{money(e.amount)}</td></tr>)}</tbody></table>{!rows.length&&<p className="empty">{t('empty')}</p>}</div>;
 return <>
 {error&&!dialog&&<p role="alert" className="error">{error}</p>}
 {page==='staff'&&<><div className="management-toolbar"><label>{t('salaryMonth')}<input type="month" value={month} onChange={e=>{if(e.target.value)setMonth(e.target.value);}}/></label><button className="primary" onClick={()=>{open('staff');setSelected('');}}><Plus size={17}/>{t('add')}</button></div><p className="muted mb-5">{t('payrollNote')}</p><div className="staff-grid">{data.staff.map(s=>{const p=payroll(data,s.id,month);return <section className="panel staff-card" key={s.id}><div className="staff-heading"><div className="staff-avatar"><Users size={22}/></div><div><h2>{s.name}</h2><p>{t(s.role)} · {s.phone||'—'}</p></div></div><div className="salary-stats"><div>{t('due')}<strong>{money(p.due)}</strong></div><div>{t('paid')}<strong>{money(p.paid)}</strong></div><div>{t('remaining')}<strong className={p.remaining?'red':''}>{money(p.remaining)}</strong></div></div><div className="staff-actions"><button onClick={()=>setProfile(s.id)}>{t('profile')}</button><button onClick={()=>open('staff',s.id)}>{t('editStaff')}</button></div></section>;})}</div>{!data.staff.length&&<div className="panel empty">{t('noStaff')}</div>}</>}
 {page==='shifts'&&<><div className="staff-grid">{data.staff.map(s=>{const active=data.shifts.find(x=>x.staffId===s.id&&x.status==='open');return <section className="panel staff-card" key={s.id}><div className="staff-heading"><Clock size={23}/><div><h2>{s.name}</h2><p>{t(s.role)}</p></div><span className={`status-pill ${active?'on-duty':''}`}>{t(active?'onDuty':'offDuty')}</span></div><p className="muted">{active?time(active.startedAt):'—'}</p><button className={active?'':'primary'} disabled={saving} onClick={()=>commit(toggleShift(data,s.id,today()))}>{t(active?'endShift':'startShift')}</button></section>;})}</div>{!data.staff.length&&<p className="panel empty">{t('noStaff')}</p>}<section className="panel mt-5"><div className="panel-head"><h3>{t('shiftHistory')}</h3></div><div className="table-wrap"><table><thead><tr>{['name','date','startedAt','endedAt','status'].map(k=><th key={k}>{t(k)}</th>)}</tr></thead><tbody>{data.shifts.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.date}</td><td>{time(s.startedAt)}</td><td>{time(s.endedAt)}</td><td>{t(s.status)}</td></tr>)}</tbody></table>{!data.shifts.length&&<p className="empty">{t('empty')}</p>}</div></section></>}
 {page==='expenses'&&<><div className="management-toolbar"><p className="muted">{t('expenses')} · AFN</p><div className="staff-actions"><button onClick={()=>open('expense')}><Plus size={17}/>{t('newExpense')}</button><button className="primary" disabled={!data.staff.length} onClick={()=>open('salary')}><Wallet size={17}/>{t('paySalary')}</button></div></div>{!data.staff.length&&<p className="muted mb-5">{t('noStaff')}</p>}<section className="panel">{history(data.expenses)}</section></>}
 {page==='settings'&&<section className="panel"><div className="panel-head"><h3>{t('settings')}</h3></div><form className="entry-form settings-form" onSubmit={async e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));if(!f.name.trim()||!f.address.trim()){setError(t('invalid'));return;}await commit({...data,settings:{name:f.name.trim(),address:f.address.trim(),theme:f.theme}});}}><label>{t('stationName')}<input name="name" defaultValue={data.settings?.name||'Northline'} required maxLength={100}/></label><label>{t('address')}<input name="address" defaultValue={data.settings?.address||'Kabul, Afghanistan'} required maxLength={250}/></label><label>{t('theme')}<select name="theme" defaultValue={data.settings?.theme||'light'}><option value="light">{t('light')}</option><option value="dark">{t('dark')}</option></select></label><div>{language}</div><p className="muted">AFN · Asia/Kabul</p><button className="primary" disabled={saving}>{t('saveSettings')}</button></form></section>}
 {profile&&(()=>{const s=data.staff.find(x=>x.id===profile),p=payroll(data,profile,month);return <Dialog title={`${t('profile')} · ${s.name}`} close={()=>setProfile(null)} t={t}><div className="entry-form"><p>{s.phone} · {t(s.role)}</p><p>{month} · {t('due')}: {money(p.due)}</p><p>{t('paid')}: {money(p.paid)} · {t('remaining')}: {money(p.remaining)}</p><p className="muted">{t('salarySnapshot')}</p><h3>{t('payments')}</h3>{history(p.payments)}</div></Dialog>;})()}
 {dialog&&<Dialog title={t(dialog==='salary'?'paySalary':dialog==='expense'?'newExpense':selected?'editStaff':'staff')} close={()=>{if(!saving)setDialog(null);}} t={t}><form onSubmit={submit} className="entry-form">
 {dialog==='staff'?<><label>{t('name')}<input autoFocus name="name" required maxLength={100} defaultValue={staff?.name||''}/></label><label>{t('role')}<select name="role" defaultValue={staff?.role||'operator'}><option value="operator">{t('operator')}</option><option value="manager">{t('manager')}</option></select></label><label>{t('phone')}<input name="phone" type="tel" defaultValue={staff?.phone||''}/></label><label>{t('salary')}<input name="salary" type="number" min="0" step="0.01" required defaultValue={staff?.salary??0}/></label><input type="hidden" name="date" value={staff?.date||today()}/><p className="muted">{t('salarySnapshot')}</p></>:<><label>{t('date')}<input autoFocus name="date" type="date" required max={today()} defaultValue={today()}/></label>{dialog==='salary'&&<><label>{t('staff')}<select value={selected} onChange={e=>setSelected(e.target.value)} required>{data.staff.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>{t('salaryMonth')}<input type="month" value={month} required onChange={e=>setMonth(e.target.value)}/></label><div className="salary-summary">{t('due')}: {money(balance.due)}<br/>{t('paid')}: {money(balance.paid)}<br/>{t('remaining')}: {money(balance.remaining)}</div></>}<label>{t('amount')}<input name="amount" type="number" min="0.01" max={dialog==='salary'?balance.remaining:undefined} step="0.01" required/></label><label>{t(dialog==='expense'?'reason':'note')}<input name={dialog==='expense'?'reason':'note'} required={dialog==='expense'} maxLength={250}/></label></>}
 {error&&<div role="alert" className="error">{error}</div>}<div className="modal-actions"><button type="button" disabled={saving} onClick={()=>setDialog(null)}>{t('cancel')}</button><button className="primary" disabled={saving||(dialog==='salary'&&balance.remaining<=0)}>{t(saving?'loading':'save')}</button></div></form></Dialog>}
 </>;
}
function Dialog({title,close,t,children}){return <div className="modal-overlay" onClick={e=>{if(e.target===e.currentTarget)close();}}><section className="modal panel" role="dialog" aria-modal="true" aria-label={title} onKeyDown={e=>{if(e.key==='Escape')close();if(e.key==='Tab'){const nodes=[...e.currentTarget.querySelectorAll('button:not(:disabled),input:not([type=hidden]),select')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}}}><div className="panel-head"><h3>{title}</h3><button onClick={close} aria-label={t('cancel')}><X size={18}/></button></div>{children}</section></div>;}
